### ISSUE TITLE
plot_posteriors out directory

### ISSUE THREAD

**Issue by andrea-mitridate** [andrea-mitridate/PTArcade#38]
`plot_posteriors` crashes when `save = False` if it does not find a directory named `plots` in the local directory. 

Possible solutions:

- change it so that a `plots` directory is created if none is found in the local directory.
- save the plot in the local directory by default 

Related to this we should allow the user to specify the output directory.

**Comment by davecwright3** [comment]
Fixed in 639c71f99973da626d31e3be494ecb9947f3329d
