### ISSUE TITLE
I installed ptarcade via pip and conda, both show successfully installed. But it alway failed when I try to import the ptarcade module. I'm work on Ubuntu 22.04 with python version 3.10.12 (conda python version 3.11). 

### ISSUE THREAD

**Issue by bqlu** [andrea-mitridate/PTArcade#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Python version [e.g. 3.10.11]
 - Python environment [e.g. conda, venv]
 - Version [e.g. 0.1.2]

**Additional context**

**Comment by andrea-mitridate** [comment]
Could you provide more details on the kind of error that you are getting when trying to import PTArcade?

Are you trying to import PTArcade in a Jupyter notebook or a Python script?
