### ISSUE TITLE
Alert user about spatial correlation limitations for certain datasets

### ISSUE THREAD

**Issue by davecwright3** [andrea-mitridate/PTArcade#48]
For NG15 the user can choose between the data with and without spatial correlations in Ceffyl mode. There is not such a choice for IPTA2 and NG12.

## Solution
Do not error out. Capture the user's config, print a statement to STDOUT that we are falling back to the available mode for the given dataset.

**Comment by andrea-mitridate** [comment]
Fixed in commit 8e935e27d6eed5f846d3a04511b4c3873468a0f0.
